site_name: knime2py
site_url: https://vitalii-kaplan.github.io/knime2py/
repo_url: https://github.com/vitalii-kaplan/knime2py
repo_name: vitalii-kaplan/knime2py

docs_dir: docs
use_directory_urls: true

theme:
  name: material
  logo: imgs/branding/logo.svg
  favicon: imgs/branding/favicon.ico

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: true
            members_order: source
            filters: ['!^_']
            docstring_style: google
  - gen-files:
      scripts:
        - docs/_scripts/gen_api.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

nav:
  - SUMMARY.md
