# Auto-generated test for KNIME workflow "KNIME2PY_UI"
# Generated by test_gen.cli — do not hand-edit; re-generate from the source workflow.

import os
import subprocess
import sys
from pathlib import Path

def test_roundtrip_knime2py_ui(output_dir: Path):
    repo_root = Path(__file__).resolve().parents[1]
    knime_proj = repo_root / "tests" / "data" / "KNIME2PY_UI"
    out_dir = output_dir  # provided by conftest.py fixture
    expected_dir = repo_root / "tests" / "data" / "data" / "KNIME2PY_UI"

    # Preconditions
    assert (knime_proj / "workflow.knime").exists(), f"Missing workflow.knime in {knime_proj}"
    assert expected_dir.exists(), f"Expected directory missing: {expected_dir}"

    # 1) Generate Python workbook(s) only, no graphs
    cmd = [
        sys.executable, "-m", "knime2py",
        str(knime_proj),
        "--out", str(out_dir),
        "--graph", "off",
        "--workbook", "py",
    ]
    env = os.environ.copy()
    env["PYTHONPATH"] = str(repo_root / "src") + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    gen = subprocess.run(cmd, capture_output=True, text=True, cwd=str(repo_root), env=env)
    assert gen.returncode == 0, f"CLI failed\nSTDOUT:\n{gen.stdout}\nSTDERR:\n{gen.stderr}"

    # 2) Locate a generated workbook script
    candidates = sorted(out_dir.glob("*_workbook.py"))
    if not candidates:
        contents = [p.name for p in out_dir.iterdir()]
        raise AssertionError(f"No *_workbook.py generated in {out_dir}. Contents: {contents}")
    if len(candidates) > 1:
        names = ", ".join(p.name for p in candidates)
        raise AssertionError(f"Expected exactly one workbook script, found multiple: {names}")
    script = candidates[0]
